import os
import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_weekly_report(df, insights: str, filename=None):
    """
    Generates a PDF report using ReportLab.
    """
    if not filename:
        date_str = datetime.datetime.now().strftime("%Y%m%d")
        os.makedirs(os.path.join(os.path.dirname(__file__), "..", "reports"), exist_ok=True)
        filename = os.path.join(os.path.dirname(__file__), "..", "reports", f"weekly_report_{date_str}.pdf")
        
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = styles['Heading1']
    title_style.alignment = 1 # Center
    
    alert_style = ParagraphStyle(
        'Alert',
        parent=styles['Normal'],
        textColor=colors.red,
        fontName='Helvetica-Bold'
    )
    
    elements = []
    
    # Header
    elements.append(Paragraph("BizMind AI - Weekly Report", title_style))
    elements.append(Spacer(1, 12))
    date_range = f"{df['date'].min().strftime('%Y-%m-%d')} to {df['date'].max().strftime('%Y-%m-%d')}"
    elements.append(Paragraph(f"Date Range: {date_range}", styles['Normal']))
    elements.append(Spacer(1, 24))
    
    # Section 1: Key Metrics
    elements.append(Paragraph("Key Metrics", styles['Heading2']))
    total_rev = df['revenue'].sum()
    total_orders = len(df)
    unique_cust = df['customer_id'].nunique()
    
    metrics_data = [
        ["Metric", "Value"],
        ["Total Revenue", f"₹{total_rev:,.2f}"],
        ["Total Orders", str(total_orders)],
        ["Unique Customers", str(unique_cust)]
    ]
    
    t = Table(metrics_data, colWidths=[200, 200])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    elements.append(t)
    elements.append(Spacer(1, 24))
    
    # Section 2: Top 5 Products
    elements.append(Paragraph("Top 5 Products", styles['Heading2']))
    top_prods = df.groupby('product')['revenue'].sum().sort_values(ascending=False).head(5)
    
    prod_data = [["Product", "Revenue"]]
    for prod, rev in top_prods.items():
        prod_data.append([prod, f"₹{rev:,.2f}"])
        
    t2 = Table(prod_data, colWidths=[200, 200])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    elements.append(t2)
    elements.append(Spacer(1, 24))
    
    # Section 3 & 4 & 5: AI Insights
    elements.append(Paragraph("AI Insights & Alerts", styles['Heading2']))
    for line in insights.split('\n'):
        if line.strip():
            if "RESTOCK NOW" in line or "ANOMALY [HIGH]" in line:
                elements.append(Paragraph(line.strip(), alert_style))
            else:
                elements.append(Paragraph(line.strip(), styles['Normal']))
            elements.append(Spacer(1, 6))
            
    elements.append(Spacer(1, 24))
    
    # Footer
    elements.append(Paragraph("Generated by BizMind AI", styles['Italic']))
    
    doc.build(elements)
    return filename
